//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoVista.PlatformManager.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlatformManagerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlatformManagerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagoVista.PlatformManager.Core.Resources.PlatformManagerResources", typeof(PlatformManagerResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Manager.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Common_GetStarted {
            get {
                return ResourceManager.GetString("Common_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Configurations.
        /// </summary>
        public static string InstanceDetails_DeviceConfigurations {
            get {
                return ResourceManager.GetString("InstanceDetails_DeviceConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeners.
        /// </summary>
        public static string InstanceDetails_Listeners {
            get {
                return ResourceManager.GetString("InstanceDetails_Listeners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Types.
        /// </summary>
        public static string InstanceDetails_MessageTypes {
            get {
                return ResourceManager.GetString("InstanceDetails_MessageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline Modules.
        /// </summary>
        public static string InstanceDetails_PipelineModules {
            get {
                return ResourceManager.GetString("InstanceDetails_PipelineModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        public static string InstanceDetails_Planner {
            get {
                return ResourceManager.GetString("InstanceDetails_Planner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string InstanceDetails_Routes {
            get {
                return ResourceManager.GetString("InstanceDetails_Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string InstanceView_Manage {
            get {
                return ResourceManager.GetString("InstanceView_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Details.
        /// </summary>
        public static string InstanceView_Title {
            get {
                return ResourceManager.GetString("InstanceView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Server Deploy Request.
        /// </summary>
        public static string ServerAction_SentDeploy {
            get {
                return ResourceManager.GetString("ServerAction_SentDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Instance Pause Request.
        /// </summary>
        public static string ServerAction_SentPause {
            get {
                return ResourceManager.GetString("ServerAction_SentPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Solution Reload Request.
        /// </summary>
        public static string ServerAction_SentReloadSolution {
            get {
                return ResourceManager.GetString("ServerAction_SentReloadSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Server Remove Request.
        /// </summary>
        public static string ServerAction_SentRemove {
            get {
                return ResourceManager.GetString("ServerAction_SentRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Server Restart Request.
        /// </summary>
        public static string ServerAction_SentReset {
            get {
                return ResourceManager.GetString("ServerAction_SentReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Container Restart Request.
        /// </summary>
        public static string ServerAction_SentResetContainer {
            get {
                return ResourceManager.GetString("ServerAction_SentResetContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Instance Start Request.
        /// </summary>
        public static string ServerAction_SentStart {
            get {
                return ResourceManager.GetString("ServerAction_SentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Instance Stop Request.
        /// </summary>
        public static string ServerAction_SentStop {
            get {
                return ResourceManager.GetString("ServerAction_SentStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Runtime Update Request.
        /// </summary>
        public static string ServerAction_SentUpdateRuntime {
            get {
                return ResourceManager.GetString("ServerAction_SentUpdateRuntime", resourceCulture);
            }
        }
    }
}
