//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoVista.PlatformManager.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlatformManagerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlatformManagerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagoVista.PlatformManager.Core.Resources.PlatformManagerResources", typeof(PlatformManagerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Manager.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Common_GetStarted {
            get {
                return ResourceManager.GetString("Common_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Configurations.
        /// </summary>
        public static string InstanceDetails_DeviceConfigurations {
            get {
                return ResourceManager.GetString("InstanceDetails_DeviceConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeners.
        /// </summary>
        public static string InstanceDetails_Listeners {
            get {
                return ResourceManager.GetString("InstanceDetails_Listeners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Types.
        /// </summary>
        public static string InstanceDetails_MessageTypes {
            get {
                return ResourceManager.GetString("InstanceDetails_MessageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline Modules.
        /// </summary>
        public static string InstanceDetails_PipelineModules {
            get {
                return ResourceManager.GetString("InstanceDetails_PipelineModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        public static string InstanceDetails_Planner {
            get {
                return ResourceManager.GetString("InstanceDetails_Planner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string InstanceDetails_Routes {
            get {
                return ResourceManager.GetString("InstanceDetails_Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string InstanceView_Manage {
            get {
                return ResourceManager.GetString("InstanceView_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Details.
        /// </summary>
        public static string InstanceView_Title {
            get {
                return ResourceManager.GetString("InstanceView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Instances.
        /// </summary>
        public static string MainMenu_AllInstances {
            get {
                return ResourceManager.GetString("MainMenu_AllInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently don&apos;t have any IoT Applications deployed, please visit our web site to build your first application..
        /// </summary>
        public static string MainView_NoPlatforms {
            get {
                return ResourceManager.GetString("MainView_NoPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy....
        /// </summary>
        public static string MonitorInstance_Busy {
            get {
                return ResourceManager.GetString("MonitorInstance_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Telemetry.
        /// </summary>
        public static string MonitorInstance_HostTelemetry {
            get {
                return ResourceManager.GetString("MonitorInstance_HostTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Actions.
        /// </summary>
        public static string MonitorInstance_InstanceActions {
            get {
                return ResourceManager.GetString("MonitorInstance_InstanceActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Information.
        /// </summary>
        public static string MonitorInstance_InstanceInformation {
            get {
                return ResourceManager.GetString("MonitorInstance_InstanceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Name.
        /// </summary>
        public static string MonitorInstance_InstanceName {
            get {
                return ResourceManager.GetString("MonitorInstance_InstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Telemetry.
        /// </summary>
        public static string MonitorInstance_InstanceTelemetry {
            get {
                return ResourceManager.GetString("MonitorInstance_InstanceTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Instance.
        /// </summary>
        public static string MonitorInstance_Title {
            get {
                return ResourceManager.GetString("MonitorInstance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Server Deploy Request.
        /// </summary>
        public static string ServerAction_SentDeploy {
            get {
                return ResourceManager.GetString("ServerAction_SentDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Instance Pause Request.
        /// </summary>
        public static string ServerAction_SentPause {
            get {
                return ResourceManager.GetString("ServerAction_SentPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Solution Reload Request.
        /// </summary>
        public static string ServerAction_SentReloadSolution {
            get {
                return ResourceManager.GetString("ServerAction_SentReloadSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Server Remove Request.
        /// </summary>
        public static string ServerAction_SentRemove {
            get {
                return ResourceManager.GetString("ServerAction_SentRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Server Restart Request.
        /// </summary>
        public static string ServerAction_SentReset {
            get {
                return ResourceManager.GetString("ServerAction_SentReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Container Restart Request.
        /// </summary>
        public static string ServerAction_SentResetContainer {
            get {
                return ResourceManager.GetString("ServerAction_SentResetContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Instance Start Request.
        /// </summary>
        public static string ServerAction_SentStart {
            get {
                return ResourceManager.GetString("ServerAction_SentStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Instance Stop Request.
        /// </summary>
        public static string ServerAction_SentStop {
            get {
                return ResourceManager.GetString("ServerAction_SentStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued Runtime Update Request.
        /// </summary>
        public static string ServerAction_SentUpdateRuntime {
            get {
                return ResourceManager.GetString("ServerAction_SentUpdateRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy.
        /// </summary>
        public static string ServerActionLink_Deploy {
            get {
                return ResourceManager.GetString("ServerActionLink_Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string ServerActionLink_Pause {
            get {
                return ResourceManager.GetString("ServerActionLink_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Solution.
        /// </summary>
        public static string ServerActionLink_ReloadSolution {
            get {
                return ResourceManager.GetString("ServerActionLink_ReloadSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ServerActionLink_Remove {
            get {
                return ResourceManager.GetString("ServerActionLink_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Server.
        /// </summary>
        public static string ServerActionLink_Reset {
            get {
                return ResourceManager.GetString("ServerActionLink_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Runtime.
        /// </summary>
        public static string ServerActionLink_ResetContainer {
            get {
                return ResourceManager.GetString("ServerActionLink_ResetContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH Into Host.
        /// </summary>
        public static string ServerActionLink_SSH {
            get {
                return ResourceManager.GetString("ServerActionLink_SSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ServerActionLink_Start {
            get {
                return ResourceManager.GetString("ServerActionLink_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string ServerActionLink_Stop {
            get {
                return ResourceManager.GetString("ServerActionLink_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Runtime.
        /// </summary>
        public static string ServerActionLink_UpdateRuntime {
            get {
                return ResourceManager.GetString("ServerActionLink_UpdateRuntime", resourceCulture);
            }
        }
    }
}
